### ISSUE TITLE
Performance for creating a sub item is terrible

### ISSUE THREAD

**Issue by ParkerWieseler** [codeflip-academy/todo#18]
Step 1: go to web surge.
Step 2: create request: http://localhost:5000/accounts/1/lists/1/todos/1/subitems
Step 3: Run Web Surge.
You'll see the output is trash.

https://user-images.githubusercontent.com/51009642/79909536-c342bd80-83e2-11ea-9e26-7910115b10d9.png

Expected behavior: failed request should be rare. average time should be at leased below 10s.

**Comment by steve-warren** [comment]
Looking at the above screenshot, it appears the load test was invalid. Closing issue.
