### ISSUE TITLE
Can leave todo item name blank when editing

### ISSUE THREAD

**Issue by trentonhicks** [codeflip-academy/todo#22]
Steps to reproduce:
1. Create a todo list item with a name.
2. Edit the todo list item and make the name field empty.
3. Save changes.

Expected behavior:
When editing a todo list item, you should not be able to save an empty item name.

**Comment by Daniel-Figueroa** [comment]
@trentonhicks When a list item is left blank it doesn't touch any back end code or even change the database. If the page is refreshed the item is still there. Can I put checks on the back end to prevent this or is it handled on the front end? In the todolistitem controller PUT method "EditTodo"  "EditItem" has the "Name" already set to [Required].

**Comment by trentonhicks** [comment]
@Daniel-Figueroa You're correct that the back-end is already handling the PUT requests correctly. The remaining work will be on proper form validation. I will take care of that. Thanks.
