### ISSUE TITLE
Todo list name can be set to nothing

### ISSUE THREAD

**Issue by trentonhicks** [codeflip-academy/todo#27]
When updating a todo list name, it appears to successfully set it to nothing, but when you refresh the page, or go back to the "My Lists" page it continues to show the previous list name.

Reproducing the issue:
1. Create a new todo list.
2. Click on the list to go to the single list view.
3. Click on the list title and change it to an empty title.
4. Press enter.
5. Go back to the "My Lists" page. You should see the list title has not been changed.

Expected behavior:
The user should get an error message saying that a list title is required.

**Comment by ParkerWieseler** [comment]
Back end is done.
