### ISSUE TITLE
TodoListItem can be created with NULL or empty name

### ISSUE THREAD

**Issue by trentonhicks** [codeflip-academy/todo#30]
When creating a todo list item you are able to set the name to NULL or an empty string.

Reproducing the issue:
1. Use Postman to create a todo list.
2. Use postman to make a POST request at this url: http://localhost:5000/accounts/1/lists/1/todos
3. Add this JSON to the POST body: `{ "todoName": null }`
4. Add another todo list item with this JSON in the POST body: `{ "todoName": "" }`
5. Both should return 200 OK.

Expected behavior:
You should not be able to create a todo list item with an empty name.

**Comment by ParkerWieseler** [comment]
Back end is done.
